#!/usr/bin/env python3
"""Every image says something, and none of them says only what it is.

    python3 tests/test_alt_text.py

Run after build.py. Three checks:

1. Every `<img>` carries an `alt` attribute. An image with no alt at all is
   read out as its filename, which on this site means a base64 data URI.
2. Every `<svg role="img">` carries `aria-label`, `aria-labelledby`, or a
   `<title>` as its first child. All three label it; any one will do.
3. No alt or label is a bare generic. "QR code" described the file format and
   sat on 10,673 pages saying nothing about where scanning it goes. A label
   naming the medium instead of the content is the failure this catches.

**Match both quote styles.** The homepage dial is generated by the moondial
sibling and writes `role='img'` in single quotes; a regex looking only for
`role="img"` skipped it silently and reported it as labelled. A checker that
misses things quietly is worse than no checker.

This does not judge whether a description is *good* — no test can. It catches
the absent and the empty-calorie, which is what regressed before.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

IMG = re.compile(r"<img\b[^>]*?>", re.I)
SVG = re.compile(r"<svg\b[^>]*?>", re.I)
ALT_ATTR = re.compile(r"""\balt\s*=\s*(['"])(.*?)\1""", re.I | re.S)
ROLE_IMG = re.compile(r"""\brole\s*=\s*['"]img['"]""", re.I)
HAS_LABEL = re.compile(r"""\baria-label(?:ledby)?\s*=\s*['"]""", re.I)
LABEL_VAL = re.compile(r"""\baria-label\s*=\s*(['"])(.*?)\1""", re.I | re.S)

# A label that names the medium and stops. Compared against the whole value,
# lowercased and stripped of punctuation — "QR code" fails, "QR code — scanning
# it opens the ... page" passes, because the second one says where it goes.
GENERIC = {
    "qr code", "qr", "image", "img", "photo", "picture", "graphic", "icon",
    "logo", "chart", "graph", "map", "diagram", "svg", "banner", "thumbnail",
    "screenshot", "illustration", "figure", "photograph", "รูป", "รูปภาพ",
    "ภาพ", "แผนที่", "กราฟ", "คิวอาร์โค้ด", "ไอคอน",
}


def flatten(s):
    return re.sub(r"[\s​]+", " ", s).strip(" .,—-–·:;").lower()


def main():
    if not DOCS.exists():
        print("docs/ is not built — run build.py first")
        return 1

    files = list(DOCS.rglob("*.html")) + list(DOCS.rglob("*.svg"))
    n_img = n_svg = 0
    no_alt, generic, unlabelled = [], [], []

    for f in files:
        t = f.read_text()
        rel = f.relative_to(DOCS)
        for tag in IMG.findall(t):
            n_img += 1
            m = ALT_ATTR.search(tag)
            if not m:
                no_alt.append((rel, tag[:90]))
                continue
            # alt="" is the correct marking for a decorative image, and is
            # deliberately not treated as a generic.
            val = flatten(m.group(2))
            if val and val in GENERIC:
                generic.append((rel, m.group(2)[:70]))
        for m in SVG.finditer(t):
            tag = m.group(0)
            if not ROLE_IMG.search(tag):
                continue
            n_svg += 1
            if not (HAS_LABEL.search(tag) or "<title>" in t[m.end():m.end() + 300]):
                unlabelled.append((rel, re.sub(r"\s+", " ", tag)[:90]))
                continue
            lm = LABEL_VAL.search(tag)
            if lm and flatten(lm.group(2)) in GENERIC:
                generic.append((rel, lm.group(2)[:70]))

    print("files scanned        %s" % f"{len(files):,}")
    print("<img> tags           %s" % f"{n_img:,}")
    print("svg role=img         %s" % f"{n_svg:,}")
    print("missing alt          %d" % len(no_alt))
    print("unlabelled svg       %d" % len(unlabelled))
    print("generic-only labels  %d" % len(generic))

    for title, rows in (("MISSING alt", no_alt), ("UNLABELLED svg", unlabelled),
                        ("GENERIC label", generic)):
        for rel, detail in rows[:10]:
            print("  %s  %s  %s" % (title, rel, detail))
        if len(rows) > 10:
            print("  ... and %d more" % (len(rows) - 10))

    if no_alt or unlabelled or generic:
        print("FAIL")
        return 1
    print("PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
