#!/usr/bin/env python3
"""Generate the browser-side birth-chart engine into assets/bazi.js.

Generated, not hand-copied, and checked by tests/test_bazi_parity.py — there is
one source of truth for this arithmetic (../taoist-oracle) and this file emits a
JavaScript restatement of it. If the two ever disagree the parity test fails and
says on which date.

The reason any of this runs in the browser: nobody should have to hand over
their birth date to be told what it means. The chart is computed locally and
transmitted only if the reader afterwards asks to be emailed a copy.

    python3 importers/make_bazi_js.py
"""
import os
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# NOT docs/ — build.py wipes that directory on every run, so anything written
# straight there is gone by the next build. build.py copies this in.
OUT = os.path.join(ROOT, "assets", "bazi.js")

JS = r"""// Birth-chart arithmetic, generated by importers/make_bazi_js.py from
// ../taoist-oracle. Do not edit here — edit there and regenerate, or the
// parity test in tests/test_bazi_parity.py will start failing.
//
// Everything below runs in the reader's browser. No birth detail is sent
// anywhere to produce a chart.
(function (global) {
  'use strict';

  var STEMS = [['甲','Jia'],['乙','Yi'],['丙','Bing'],['丁','Ding'],['戊','Wu'],
               ['己','Ji'],['庚','Geng'],['辛','Xin'],['壬','Ren'],['癸','Gui']];
  var BRANCHES = [['子','Zi','Rat'],['丑','Chou','Ox'],['寅','Yin','Tiger'],
                  ['卯','Mao','Rabbit'],['辰','Chen','Dragon'],['巳','Si','Snake'],
                  ['午','Wu','Horse'],['未','Wei','Goat'],['申','Shen','Monkey'],
                  ['酉','You','Rooster'],['戌','Xu','Dog'],['亥','Hai','Pig']];
  // Wood, Fire, Earth, Metal, Water — same order as taoist-oracle's wuxing.
  var ELEMENTS = [['木','Wood'],['火','Fire'],['土','Earth'],['金','Metal'],['水','Water']];
  var STEM_ELEMENT = [0,0,1,1,2,2,3,3,4,4];
  var BRANCH_ELEMENT = [4,2,0,0,2,1,1,2,3,3,2,4];

  function gregorianToJD(y, m, d, hour) {
    hour = hour || 0;
    if (m <= 2) { y -= 1; m += 12; }
    var a = Math.floor(y / 100), b = 2 - a + Math.floor(a / 4);
    return Math.floor(365.25 * (y + 4716)) + Math.floor(30.6001 * (m + 1))
         + d + b - 1524.5 + hour / 24;
  }
  var CST = 8 / 24;
  function midnightJD(y, m, d) { return gregorianToJD(y, m, d) - CST; }

  // 2000-01-07 CST is 甲子, index 0 — the standard published anchor day.
  var DAY_ANCHOR = midnightJD(2000, 1, 7);

  function mod(n, k) { return ((n % k) + k) % k; }

  function combine(stem, branch) {
    for (var i = 0; i < 60; i++) {
      if (i % 10 === stem && i % 12 === branch) return i;
    }
    return -1;                       // stem/branch parity mismatch: impossible pair
  }

  function pillar(index) {
    var i = mod(index, 60), s = i % 10, b = i % 12;
    return {
      index: i, stem: s, branch: b,
      zh: STEMS[s][0] + BRANCHES[b][0],
      pinyin: STEMS[s][1] + ' ' + BRANCHES[b][1],
      animal: BRANCHES[b][2],
      element: STEM_ELEMENT[s],
      branchElement: BRANCH_ELEMENT[b],
      elementZh: ELEMENTS[STEM_ELEMENT[s]][0],
      elementEn: ELEMENTS[STEM_ELEMENT[s]][1]
    };
  }

  function dayOfYear(y, m, d) {
    return Math.round((Date.UTC(y, m - 1, d) - Date.UTC(y, 0, 1)) / 86400000) + 1;
  }

  // TERMS.years[Y] is twelve Julian Days (UT) — the 節 that open BaZi year Y's
  // months. A term is an INSTANT: at noon on 1926-02-04 the sun is still at
  // 314.933 deg, so 立春 has not happened and that birth belongs to the previous
  // month. Comparing dates rather than moments gets those births wrong.
  function termJD(TERMS, year, i) {
    var row = TERMS.years[String(year)];
    return row ? row[i] : null;
  }

  function chart(TERMS, y, m, d, hour, hasHour) {
    if (!TERMS.years[String(y)]) return { error: 'out-of-range', from: TERMS.from, to: TERMS.to };
    // Noon UT when the hour is unknown, matching taoist-oracle's own default.
    var bornJD = gregorianToJD(y, m, d, hasHour ? hour : 12);

    // Year pillar — the BaZi year turns at 立春, not 1 January.
    //
    // NOTE, and it is deliberate: taoist-oracle's year_pillar compares CIVIL
    // DAYS (is the birth day before 立春's day?) while its month_pillar compares
    // the solar INSTANT. Those two disagree for anyone born on the day of 立春
    // itself. We reproduce the civil-day rule here so there is exactly one
    // source of truth and the parity test stays meaningful — see the note in
    // tests/test_bazi_parity.py. Fix it there first, then regenerate.
    var lichunJD = termJD(TERMS, y, 0);
    var lichunDay = lichunJD === null ? null : Math.floor(lichunJD + CST + 0.5);
    var bornDay = Math.floor(gregorianToJD(y, m, d) + CST + 0.5);
    var by = (lichunDay !== null && bornDay < lichunDay) ? y - 1 : y;
    var yp = pillar(mod(by - 4, 60));

    // Month pillar — the last 節 we have passed inside this BaZi year.
    var order = 11;
    for (var i = 11; i >= 0; i--) {
      var t = termJD(TERMS, by, i);
      if (t !== null && bornJD >= t) { order = i; break; }
    }
    var mBranch = mod(order + 2, 12);
    var mStem = mod((yp.stem % 5) * 2 + 2 + order, 10);
    var mp = pillar(combine(mStem, mBranch));

    // Day pillar — pure 60-cycle from the anchor.
    var dp = pillar(mod(Math.round(midnightJD(y, m, d) - DAY_ANCHOR), 60));

    // Hour pillar — 五鼠遁 from the day stem. Only if the hour is known.
    var hp = null;
    if (hasHour) {
      var hBranch = mod(Math.floor((hour + 1) / 2), 12);
      var hStem = mod((dp.stem % 5) * 2 + hBranch, 10);
      hp = pillar(combine(hStem, hBranch));
    }

    var pillars = { year: yp, month: mp, day: dp, hour: hp };
    var tally = [0, 0, 0, 0, 0];
    ['year', 'month', 'day', 'hour'].forEach(function (k) {
      var p = pillars[k];
      if (!p) return;
      tally[p.element] += 1;
      tally[p.branchElement] += 1;
    });
    return {
      pillars: pillars,
      hasHour: !!hasHour,
      dayMaster: { stem: dp.stem, zh: STEMS[dp.stem][0], pinyin: STEMS[dp.stem][1],
                   element: dp.element, elementZh: ELEMENTS[dp.element][0],
                   elementEn: ELEMENTS[dp.element][1] },
      elements: tally,
      elementNames: ELEMENTS
    };
  }

  global.MDBazi = {
    chart: chart, pillar: pillar, STEMS: STEMS, BRANCHES: BRANCHES,
    ELEMENTS: ELEMENTS, dayOfYear: dayOfYear
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
"""


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    header = (f"// generated {date.today().isoformat()} — "
              f"source of truth: ../taoist-oracle (core/ganzhi.py, core/calendar_cn.py)\n")
    with open(OUT, "w") as fh:
        fh.write(header + JS)
    print(f"🐜 birth-chart engine -> {OUT} ({os.path.getsize(OUT):,} bytes)")


if __name__ == "__main__":
    main()
